MAX_PLAYERS = 12
SET_SIZE = 3
STANDARD_FIELD_SIZE = 12

default_id = "id1"
default_name = "leverett"

GRID_WIDTH = 3
HINT_FLASHES = 3
HIGHLIGHT_COLOR = (1, 0, 0, 0.69)
FLASH_COLOR = (1, 0, 0, 1)
FLASH_INTERVAL = 0.12
GAME_OVER = "Game Over"